steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_KEY=${_NEXT_PUBLIC_SUPABASE_KEY}'
      - '--build-arg'
      - 'OPENAI_API_KEY=${_OPENAI_API_KEY}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL},NEXT_PUBLIC_SUPABASE_KEY=${_NEXT_PUBLIC_SUPABASE_KEY},OPENAI_API_KEY=${_OPENAI_API_KEY}'

substitutions:
  _SERVICE_NAME: your-service-name
  _REGION: us-central1
  _NEXT_PUBLIC_SUPABASE_URL: ''  # Set this in Cloud Build trigger substitutions
  _NEXT_PUBLIC_SUPABASE_KEY: ''  # Set this in Cloud Build trigger substitutions
  _OPENAI_API_KEY: ''  # Set this in Cloud Build trigger substitutions

options:
  logging: CLOUD_LOGGING_ONLY

